services:
  webserver:
    image: yiisoftware/yii2-php:8.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - postgres
    # Добавляем установку зависимостей прямо перед выполнением основного скрипта
    command: >
      bash -c "
        composer install && 
        npm ci && 
        npm run css-dev && 
        npm run dev && 
        bash refresh.sh
      "
    environment:
      PHP_ENABLE_XDEBUG: 1
      XDEBUG_MODE: "coverage"
      # Добавляем переменные окружения, чтобы скрипты знали куда стучаться
      DATABASE_URL: "postgres://vacation:secret@postgres:5432/app-vacations"

  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_DB: "app-vacations"
      POSTGRES_USER: "vacation"
      POSTGRES_PASSWORD: "secret"
    ports:
      - '5432:5432'

  # Раскомментировать для запуска тестов
  # postgres-test:
  #   image: postgres:17.0
  #   environment:
  #     POSTGRES_DB: "app-vacations-test"
  #     POSTGRES_USER: "vacation"
  #     POSTGRES_PASSWORD: "secret"
  #   ports:
  #     - '5433:5432'
