services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app:delegated
      - /app/vendor
      - /app/web/assets
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    ports:
      - '8000:80'
    depends_on:
      - postgres
    command: >
      bash -c "chmod +x refresh.sh && ./refresh.sh"
    environment:
      PHP_ENABLE_XDEBUG: 1
      XDEBUG_MODE: "coverage"
      DB_DSN: "pgsql:host=postgres;port=5432;dbname=app-vacations"
      DB_USER: "vacation"
      DB_PASSWORD: "secret"

  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_DB: "app-vacations"
      POSTGRES_USER: "vacation"
      POSTGRES_PASSWORD: "secret"
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
